services:
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: vehicle_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  minio:
    image: cgr.dev/chainguard/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
  
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  pricing-postgres:
    image: postgres:15-alpine
    container_name: pricing_postgres
    restart: always
    environment:
      POSTGRES_DB: pricing_db
      POSTGRES_USER: pricing_user
      POSTGRES_PASSWORD: pricing_secret
    ports:
      - "5433:5432"
    volumes:
      - pricing_pg_data:/var/lib/postgresql/data
      - ./init-pricing.sql:/docker-entrypoint-initdb.d/init-pricing.sql

volumes:
  pricing_pg_data:
  minio_data:
  pgdata: